"""
Сборка фронтенда без Node.js: бандл app.js + синхронизация dist/index.html.
Запуск: python build_frontend.py
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC_APP = ROOT / "src" / "app.js"
DIST = ROOT / "dist"
DIST_ASSETS = DIST / "assets"
BUNDLE_NAME = "app.bundle.js"
CSS_NAME = "style-live-20260522.css"
INDEX_SRC = ROOT / "index.html"
INDEX_DIST = DIST / "index.html"


def build_js_bundle() -> Path:
    code = SRC_APP.read_text(encoding="utf-8")
    code = code.replace(
        "import.meta.env.VITE_API_BASE || '/api'",
        "'/api'",
    )
    code = code.replace(
        "import.meta.env.VITE_MEDIA_ORIGIN ?? ''",
        "''",
    )
    code = re.sub(
        r"export\s+async\s+function\s+init\s*\(",
        "async function init(",
        code,
        count=1,
    )

    bootstrap = """
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', () => { init(); });
} else {
    init();
}
"""

    bundle = (
        "/* AutoPro bundle — generated by build_frontend.py */\n"
        "(function () {\n"
        "'use strict';\n"
        f"{code}\n"
        f"{bootstrap}"
        "})();\n"
    )

    DIST_ASSETS.mkdir(parents=True, exist_ok=True)
    out = DIST_ASSETS / BUNDLE_NAME
    out.write_text(bundle, encoding="utf-8")
    return out


def build_index_html() -> None:
    html = INDEX_SRC.read_text(encoding="utf-8")

    # Убираем stub и dev-модуль — в prod один синхронный бандл в конце страницы.
    html = re.sub(
        r"\s*<script>\s*\(function \(\) \{.*?</script>\s*",
        "\n",
        html,
        count=1,
        flags=re.DOTALL,
    )
    html = html.replace(
        '<script type="module" src="/src/main.js"></script>',
        f'<script src="/assets/{BUNDLE_NAME}"></script>',
    )

    if f'/assets/{CSS_NAME}' not in html:
        html = html.replace(
            "</head>",
            f'    <link rel="stylesheet" href="/assets/{CSS_NAME}">\n</head>',
        )

    DIST.mkdir(parents=True, exist_ok=True)
    INDEX_DIST.write_text(html, encoding="utf-8")


def main() -> None:
    bundle_path = build_js_bundle()
    build_index_html()
    print(f"[OK] JS bundle: {bundle_path} ({bundle_path.stat().st_size} bytes)")
    print(f"[OK] HTML: {INDEX_DIST}")


if __name__ == "__main__":
    main()
