"""

Сборка фронтенда: CSS через Vite + бандл app.js + dist/index.html.

Запуск: python build_frontend.py

"""

from __future__ import annotations



import re

import shutil

import subprocess

from pathlib import Path



ROOT = Path(__file__).resolve().parent

SRC_APP = ROOT / "src" / "app.js"

DIST = ROOT / "dist"

DIST_ASSETS = DIST / "assets"

BUNDLE_NAME = "app.bundle.js"

INDEX_SRC = ROOT / "index.html"

INDEX_DIST = DIST / "index.html"





def find_node_cmd() -> str | None:

    node = shutil.which("node")

    if node:

        return node

    for candidate in (

        Path(r"C:\Program Files\nodejs\node.exe"),

        Path(r"C:\Program Files (x86)\nodejs\node.exe"),

    ):

        if candidate.exists():

            return str(candidate)

    return None





def run_vite_build() -> bool:

    """Собирает Tailwind/CSS (и временно весь dist) через Vite."""

    if not (ROOT / "package.json").exists():

        print("[--] package.json не найден — пропуск Vite")

        return False

    if not (ROOT / "node_modules" / "vite" / "bin" / "vite.js").exists():

        print("[--] node_modules не установлены. Выполните: cd frontend && npm install")

        return False



    node = find_node_cmd()

    if not node:

        print("[--] Node.js не найден — CSS не пересобран")

        return False



    vite_js = ROOT / "node_modules" / "vite" / "bin" / "vite.js"

    print("> node", vite_js, "build")

    subprocess.run([node, str(vite_js), "build"], cwd=str(ROOT), check=True)

    return True





def resolve_css_href() -> str | None:

    """Возвращает путь вида /assets/index-XXXX.css из последней сборки Vite."""

    if not DIST_ASSETS.exists():

        return None

    css_files = sorted(

        DIST_ASSETS.glob("index-*.css"),

        key=lambda path: path.stat().st_mtime,

        reverse=True,

    )

    if css_files:

        return f"/assets/{css_files[0].name}"

    return None





def build_js_bundle() -> Path:

    code = SRC_APP.read_text(encoding="utf-8")

    code = code.replace(

        "import.meta.env.VITE_API_BASE || '/api'",

        "'/api'",

    )

    code = code.replace(

        "import.meta.env.VITE_MEDIA_ORIGIN ?? ''",

        "''",

    )

    code = re.sub(

        r"export\s+async\s+function\s+init\s*\(",

        "async function init(",

        code,

        count=1,

    )



    bootstrap = """

if (document.readyState === 'loading') {

    document.addEventListener('DOMContentLoaded', () => { init(); });

} else {

    init();

}

"""



    bundle = (

        "/* AutoPro bundle — generated by build_frontend.py */\n"

        "(function () {\n"

        "'use strict';\n"

        f"{code}\n"

        f"{bootstrap}"

        "})();\n"

    )



    DIST_ASSETS.mkdir(parents=True, exist_ok=True)

    out = DIST_ASSETS / BUNDLE_NAME

    out.write_text(bundle, encoding="utf-8")

    return out





def build_index_html(css_href: str) -> None:

    html = INDEX_SRC.read_text(encoding="utf-8")



    # Убираем stub и dev-модуль — в prod один синхронный бандл в конце страницы.

    html = re.sub(

        r"\s*<script>\s*\(function \(\) \{.*?</script>\s*",

        "\n",

        html,

        count=1,

        flags=re.DOTALL,

    )

    html = html.replace(

        '<script type="module" src="/src/main.js"></script>',

        f'<script src="/assets/{BUNDLE_NAME}"></script>',

    )



    # Удаляем старые ссылки на CSS (в т.ч. устаревший style-live-*.css)

    html = re.sub(r'\s*<link rel="stylesheet" href="/assets/[^"]+\.css">\s*', "\n", html)

    html = html.replace(

        "</head>",

        f'    <link rel="stylesheet" href="{css_href}">\n</head>',

    )



    DIST.mkdir(parents=True, exist_ok=True)

    INDEX_DIST.write_text(html, encoding="utf-8")





def main() -> None:

    vite_ok = False

    try:

        vite_ok = run_vite_build()

    except subprocess.CalledProcessError as exc:

        print(f"[!!] Vite build failed: {exc}")



    css_href = resolve_css_href()

    if not css_href:

        raise SystemExit(

            "Не найден собранный CSS в frontend/dist/assets.\n"

            "Установите Node.js, выполните в frontend: npm install && npm run build\n"

            "или запустите build.py снова после npm install."

        )



    bundle_path = build_js_bundle()

    build_index_html(css_href)



    print(f"[OK] CSS: {css_href}" + (" (Vite)" if vite_ok else " (существующий файл)"))

    print(f"[OK] JS bundle: {bundle_path} ({bundle_path.stat().st_size} bytes)")

    print(f"[OK] HTML: {INDEX_DIST}")





if __name__ == "__main__":

    main()


